#!/bin/bash
#
# this is kind of dirty nasty, but create directories, then upload
#

VER=$(cat ../aokpcb/vendor/aokp/products/common_versions.mk | grep "TARGET_PRODUCT" | cut -f3 -d '_' | cut -f1 -d ' ')
NAME=pcbblue_$1_$VER.zip
mkdir -p ~/public_html/$1
cp ./$NAME ~/public_html/$1/aokpcb_$1_$VER-$(date +%Y%m%d-%H%M).zip &
cd ~/public_html/$1/
md5sum aokpcb_$1_$VER-$(date +%Y%m%d-%H%M).zip | cat >> aokpcb_$1_$VER-$(date +%Y%m%d-%H%M).zip.md5
