#!/bin/bash
#
# this is kind of dirty nasty, but create directories, then upload
#

VER=$(cat /home/remicks/android/AOKPCB/vendor/aokp/configs/common_versions.mk | grep "TARGET_PRODUCT" | cut -f3 -d '_' | cut -f1 -d ' ')
NAME=aokpcb_$1_$VER.zip
cp ./$NAME /home/remicks/public_html/$1/aokpcb_$1_$VER-$(date +%Y%m%d-%H%M).zip
cd /home/remicks/public_html/$1/
md5sum aokpcb_$1_$VER-$(date +%Y%m%d-%H%M).zip | cat >> aokpcb_$1_$VER-$(date +%Y%m%d-%H%M).zip.md5

# Companion app area
cd ~/private_html
mkdir -p app/$1
rm app/$1.txt
echo "1" >> app/$1.txt
echo "http://aokpcb.boom.net/nightlies/$1/aokpcb_$1_$VER-$(date +%Y%m%d-%H%M).zip" >> app/$1.txt
